### ISSUE TITLE
Fresh Install -g throws error on store.json 

### ISSUE THREAD

**Issue by eighteyes** [matrix-io/matrix-cli#23]
`` 
Error: EACCES: permission denied, open '/usr/local/lib/node_modules/matrix-cli/lib/../store.json'
``
Need to figure out now to not need `sudo` to persist information. I am not clear as to where is a safe place to store this kind of information. I don't know enough about unix file structure and permissions. @maciekrb any ideas?

**Comment by diegoribero** [comment]
It's not failing for me, but that's probably because I changed the ownership of _**/usr/local/lib/node_modules**_,  _**/usr/local/bin**_ and _**/usr/local/share**_ with `sudo chown -R $(whoami) $(npm config get prefix)/{lib/node_modules,bin,share}`
Took that idea from https://docs.npmjs.com/getting-started/fixing-npm-permissions

As that link suggests, an alternative is to change npm's default directory to another directory. 
That might be a good approach

**Comment by eighteyes** [comment]
Fixed
